version: '3'

services:
  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    deploy:
      resources:
        limits:
          memory: 1G

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:5.5.3
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
      - xpack.security.enabled=false